spring.datasource.url=jdbc:postgresql://localhost:5432/CloudFileStorage
spring.datasource.username=postgres
spring.datasource.password=postgres

minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket=user-files