spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

minio.endpoint=${MINIO_URL}
minio.access-key=${MINIO_USERNAME}
minio.secret-key=${MINIO_PASSWORD}
minio.bucket=${MINIO_BUCKET}