spring.application.name=cloud-storage

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.profiles.active=${SPRING_PROFILE:dev}

spring.data.redis.host=redis
spring.data.redis.port=6379